
[phases.setup]
aptPkgs = ['libzbar-dev', 'libzbar0', 'zbar-tools']
nixPkgs = ['python311Packages.pyzbar']

[phases.install]
cmd = 'python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt'

[start]
cmd = 'python3 main.py'
